name: Gitattributes Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_gitattributes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check .gitattributes file
        run: |
          # Get the list of directories from .gitattributes
          directories=$(grep '^\S' .gitattributes | awk '{print $1}' | grep -v 'merge=ours')
          
          # Check each directory for specific words (modify 'pet|traker' as needed)
          for dir in $directories; do
            echo "Checking directory: $dir"
            if find "$dir" -type f -exec grep -i -H -n -E 'word1|word2' {} +; then
              echo "Error: Found forbidden words in files within $dir."
              exit 1
            fi
          done
