name: Word Exclusion

on:
  push:
    branches:
      - 'testing'
  pull_request_target:
    branches:
      - 'testing'

jobs:
  word_exclusion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PowerShell Core
        run: |
          wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
      
      - name: Get file list from .gitattributes in main branch
        id: get_file_list
        run: |
          git show origin/testing:.gitattributes > gitattributes_temp.txt
          echo "Content of gitattributes_temp.txt:"
          Get-Content -Path gitattributes_temp.txt
          $FileList = Get-Content -Path gitattributes_temp.txt |
                      Select-Object -Skip 17 |
                      Select-String -Pattern '^(.*?)(?=\smerge=ours|$)' |
                      ForEach-Object { $_.Matches.Groups[1].Value }

          echo "Content of the extracted file list:"
          $FileList

          if ($FileList.Count -eq 0) {
            echo "No files were extracted from .gitattributes. Check the pattern or file content."
            exit 1
          }
          $FileList | Out-File -Encoding ASCII file_list.txt
        shell: pwsh

      - name: Run Word Exclusion script
        run: |
          $Patterns = @("private", "pets*", "tracker*")
          $PathToCheck = $env:GITHUB_WORKSPACE
          $Matches = @()
          # Read the list of changed files (for PR) or the list of all files (for push)
          if ($env:GITHUB_BASE_REF) {
            # If GITHUB_BASE_REF exists, this is a pull request
            git diff --name-only $env:GITHUB_BASE_REF...$env:GITHUB_HEAD_REF > changed_files.txt
          }
          else {
            # Otherwise, this is a push event
            git ls-tree --name-only HEAD > changed_files.txt
          }
          # Read the list of files to check from .gitattributes
          $FileList = Get-Content file_list.txt
          # Find matches in directory names and file names for changed files
          Get-Content changed_files.txt | ForEach-Object {
              $Type = if (Test-Path $_ -PathType Container) { "dir" } else { "filename" }
              $Name = $_
              foreach ($Pattern in $Patterns) {
                  if ($Name -like "*$Pattern*") {
                      $Matches += New-Object PSObject -Property @{
                          Type = $Type
                          Match = $Pattern
                          Name = $Name
                      }
                  }
              }
          }
          # Find matches in file contents for changed files
          Get-Content changed_files.txt | ForEach-Object {
              $FileName = $_
              foreach ($Pattern in $Patterns) {
                  if (Select-String -Path $FileName -Pattern $Pattern -Quiet) {
                      $Matches += New-Object PSObject -Property @{
                          Type = "file"
                          Match = $Pattern
                          Name = $FileName
                      }
                  }
              }
          }

          # Find matches in directory names and file names for files to check from .gitattributes
          $NotFoundPaths = @()
          Write-Output "File List: $FileList"
          $FileList | ForEach-Object {
                $Type = if (Test-Path $_ -PathType Container) { "dir" } else { "filename" }
                $Name = $_
                foreach ($Pattern in $Patterns) {
                  try {
                      if ($Name -match "*$Pattern*") {
                          $Matches += New-Object PSObject -Property @{
                              Type = $Type
                              Match = $Pattern
                              Name = $Name
                          }
                      }
                  }
                }
           }

          # Find matches in file contents for files to check from .gitattributes
          $FileList | ForEach-Object {
              $FileName = $_
              foreach ($Pattern in $Patterns) {
                  if (Select-String -Path $FileName -Pattern $Pattern -Quiet) {
                      $Matches += New-Object PSObject -Property @{
                          Type = "file"
                          Match = $Pattern
                          Name = $FileName
                      }
                  }
              }
          }
          # Output matches
          $Matches
          # Convert the matches to JSON format
          $MatchesJson = $Matches | ConvertTo-Json -Depth 100
          Write-Output $MatchesJson | Out-File matches.json

          # Fail the pipeline if matches.json is not empty
          if ((Get-Content -Path matches.json -Raw) -ne "") {
            echo "Word exclusion matches found."
            exit 1
          }
        shell: pwsh  # Use the PowerShell shell to execute the script

      - name: Export .gitattributes file list as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: file_list
          path: file_list.txt
          
      - name: Upload JSON output
        uses: actions/upload-artifact@v2
        with:
          name: matches
          path: matches.json
