name: Word Exclusion

on:
  push:
    branches:
      - 'tmo-main'
    paths:
      - 'scripts/**' # Adjust the path to the folder or specific files you want to monitor
      - 'doc/**'     # Add additional paths if needed

jobs:
  word_exclusion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PowerShell Core
        run: |
          # Import the Microsoft repository GPG key
          wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          # Install PowerShell Core
          sudo apt-get update
          sudo apt-get install -y powershell
      - name: Run Word Exclusion script
        run: |
          $Patterns = @("private", "pets*", "tracker*")
          $RootPath = $env:GITHUB_WORKSPACE  # This variable points to the root of the checked-out repository
          $WordExcludeList = @("snippet")
          $Matches = @()

          # Define the full paths to the selected folders in the root directory
          $SelectedFolderPaths = $SelectedFolders | ForEach-Object { Join-Path -Path $RootPath -ChildPath $_ }

          # Find matches in directory names and file names within the selected folders in the root directory
          Get-ChildItem -Path $SelectedFolderPaths -Recurse | ForEach-Object {
              $Type = if ($_.PSIsContainer) { "dir" } else { "filename" }
              $Name = $_.FullName

              foreach ($Pattern in $Patterns) {
                  # Check if the current pattern is not in the word exclude list
                  if ($WordExcludeList -notcontains $Pattern) {
                      if ($Name -like "*$Pattern*") {
                          $Matches += New-Object PSObject -Property @{
                              Type = $Type
                              Match = $Pattern
                              Name = $Name
                          }
                      }
                  }
              }
          }

          # Find matches in file contents within the selected folders in the root directory
          Get-ChildItem -Path $SelectedFolderPaths -Recurse -File | ForEach-Object {
              $FileName = $_.FullName

              foreach ($Pattern in $Patterns) {
                  # Check if the current pattern is not in the word exclude list
                  if ($WordExcludeList -notcontains $Pattern) {
                      if (Select-String -Path $FileName -Pattern $Pattern -Quiet) {
                          $Matches += New-Object PSObject -Property @{
                              Type = "file"
                              Match = $Pattern
                              Name = $FileName
                          }
                      }
                  }
              }
          }

          # Output matches
          $Matches

          # Convert the matches to JSON format
          $MatchesJson = $Matches | ConvertTo-Json -Depth 100
          Write-Output $MatchesJson | Out-File matches.json
        shell: pwsh  # Use the PowerShell shell to execute the script


      - name: Upload JSON output
        uses: actions/upload-artifact@v2
        with:
          name: matches
          path: matches.json
